[2021-06-25 15:26:54,620] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-06-24T00:00:00+00:00 [queued]>
[2021-06-25 15:26:54,628] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-06-24T00:00:00+00:00 [queued]>
[2021-06-25 15:26:54,628] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 15:26:54,628] {taskinstance.py:1068} INFO - Starting attempt 7 of 7
[2021-06-25 15:26:54,628] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 15:26:54,634] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-06-24T00:00:00+00:00
[2021-06-25 15:26:54,639] {standard_task_runner.py:52} INFO - Started process 32297 to run task
[2021-06-25 15:26:54,644] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-06-24T00:00:00+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/var/folders/9t/2jnn4bv95w9552ldckktgq900000gn/T/tmpahqvit5l', '--error-file', '/var/folders/9t/2jnn4bv95w9552ldckktgq900000gn/T/tmpjveahvos']
[2021-06-25 15:26:54,645] {standard_task_runner.py:77} INFO - Job 12: Subtask is_api_available
[2021-06-25 15:26:54,664] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-06-24T00:00:00+00:00 [running]> on host saidamirs-macbook-pro.local
[2021-06-25 15:26:54,678] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-06-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-24T00:00:00+00:00
[2021-06-25 15:26:54,678] {http.py:101} INFO - Poking: api/
[2021-06-25 15:26:54,680] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-06-25 15:26:54,681] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-06-25 15:26:54,749] {local_task_job.py:151} INFO - Task exited with return code Negsignal.SIGABRT
